version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      timezone: Europe/London
    assignees:
      - "revett"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
