issues:
  exclude:
    - G404
    - ST1000
  exclude-use-default: false
linters:
  disable:
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - godox
    - goerr113
    - golint # The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner. Replaced by revive.
    - interfacer # The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.
    - maligned # The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner. Replaced by govet 'fieldalignment'.
    - nlreturn
    - scopelint # The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner. Replaced by exportloopref.
    - wsl
  enable-all: true
linters-settings:
  varnamelen:
    ignore-names:
      - fn
      - id
run:
  concurrency: 4
  timeout: 30s
