issues:
  exclude:
    - G404
    - ST1000
  exclude-use-default: false
linters:
  disable:
    - exhaustivestruct
    - exhaustruct
    - goerr113
    - nlreturn
    - wsl
  enable-all: true
linters-settings:
  varnamelen:
    ignore-names:
      - id
run:
  concurrency: 4
  timeout: 30s
