#!/usr/bin/env bash

# Variables

HOUR=$(date "+%H")
MINUTE=$(date "+%M")
SECOND=$(date "+%S")
DAY=$(date "+%d")
MONTH=$(date "+%m")
YEAR=$(date "+%Y")
TIMESTAMP=$(date "+%s")
HUMAN_DATETIME=$(date)

DATE="$YEAR.$MONTH.$DAY"
TIME="$HOUR$MINUTE"
DATETIME="$DATE.$TIME"

UNIQUE_PHRASE=$(gshuf -n 4 /usr/share/dict/words | tr -s '\n' '-' | sed 's/.$//' | awk '{print tolower($0)}')

FRONTMATTER="---
// cspell:disable-next-line
id: $UNIQUE_PHRASE
created: $TIMESTAMP ($HUMAN_DATETIME)
---
"

GRAY='\033[0;30m'
PURPLE='\033[1;35m'
NC='\033[0m' # No Color

# Logic

if [ "$#" -lt 1 ]; then
  echo "error: must pass at least one argument"
  exit 1
fi
NOTE_TYPE=$1

ACCEPTED_NOTE_TYPES=("area entity interview project scratch system")
if [[ ! " ${ACCEPTED_NOTE_TYPES[*]} " =~ " ${NOTE_TYPE} " ]]; then
  echo "error: unknown note type"
  exit 1
fi

case $NOTE_TYPE in
  area)
    echo -e -n "[1/2] ${PURPLE}area${NC} (e.g. 'coffee'):\n> "
    read -e AREA
    echo -e -n "[2/2] ${PURPLE}title${NC} (e.g. 'london-roasters'):\n> "
    read -e TITLE
    FILENAME="area.$AREA.$TITLE.md"
    echo "$FRONTMATTER" > $FILENAME
    cat templates/area.md >> $FILENAME
    code $FILENAME
    ;;

  entity)
    echo -e -n "[1/1] ${PURPLE}thing${NC} (e.g. 'person.friend.john-smith'):\n> "
    read -e THING
    FILENAME="entity.$THING.md"
    echo "$FRONTMATTER" > $FILENAME
    cat templates/entity.md >> $FILENAME
    code $FILENAME
    ;;

  interview)
    FILENAME="interview.$DATETIME.md"
    echo "$FRONTMATTER" > $FILENAME
    cat templates/interview.md >> $FILENAME
    code $FILENAME
    ;;

  project)
    echo -e -n "[1/2] ${PURPLE}project${NC} (e.g. 'video-app'):\n> "
    read -e PROJECT
    echo -e -n "[2/2] ${PURPLE}title${NC} (e.g. 'mvp-features'):\n> "
    read -e TITLE
    FILENAME="project.$PROJECT.$TITLE.md"
    echo "$FRONTMATTER" > $FILENAME
    cat templates/project.md >> $FILENAME
    code $FILENAME
    ;;

  scratch)
    FILENAME="scratch.$DATETIME$SECOND.md"
    echo "$FRONTMATTER" > $FILENAME
    cat templates/scratch.md >> $FILENAME
    code $FILENAME
    ;;

  system)
    echo -e -n "[1/1] ${PURPLE}title${NC} (e.g. 'monthly-accounts'):\n> "
    read -e TITLE
    FILENAME="system.$TITLE.md"
    echo "$FRONTMATTER" > $FILENAME
    cat templates/system.md >> $FILENAME
    code $FILENAME
    ;;

  *)
    echo "error: unknown note type"
    exit 1
    ;;
esac
