name: Lint
on: push
permissions:
  contents: read
jobs:
  golangci:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
