name: Test
on: push
permissions:
  contents: read
jobs:
  test:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          # "1.20" must be in quotes.
          # https://github.com/actions/setup-go/issues/328
          go-version: "1.20"
      - name: Test
        run: go test -race ./...
