name: Version
on: push
permissions:
  contents: read
jobs:
  golangci:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Main Version
        run: echo "MAIN_VERSION=$(curl -s https://raw.githubusercontent.com/revett/sepias/main/VERSION)" >> $GITHUB_ENV
        shell: bash
      - name: Output Main Versions
        run: echo "${{ env.MAIN_VERSION }}"
