name: Version
on:
  push:
    branches-ignore:
      - main
permissions:
  contents: read
jobs:
  golangci:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Main Version
        run: echo "MAIN_VERSION=$(curl -s https://raw.githubusercontent.com/revett/sepia/main/VERSION)" >> $GITHUB_ENV
      - name: Output Main Version
        run: echo "${{ env.MAIN_VERSION }}"
      - name: Get Branch Version
        run: echo "BRANCH_VERSION=$(cat ./VERSION)" >> $GITHUB_ENV
      - name: Output Branch Version
        run: echo "${{ env.BRANCH_VERSION }}"
      - name: Compare Versions
        run: '[[ "${{ env.MAIN_VERSION }}" != "${{ env.BRANCH_VERSION }}" ]]'
